In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
data_path = "/home/andy/CryptoTradingPlatform/Historical"

def import_data_from_multiple_csv(path,symbol,interval):
   
    col_names = ["Open","High","Low","Close","Volumn","Close Time", "Quote Asset Volumn", "Number of Trades", "Taker Buy Base Asset Volumn", "Taker Buy Quote Asset Volumn", "Ignore" ]
    filenames = glob.glob("{}/{}/{}/*.csv".format(path,interval,symbol))
    dfs = []

    for filename in filenames:
        dfs.append(pd.read_csv(filename, names = col_names))

    data = pd.concat(dfs)
    data.index.name = "Date"

    data = data.sort_index(ascending=True)

    data["Date Time"] = pd.to_datetime(data.index,unit="ms",utc=True)

    data.index.name = "Open Time"

    return data

def write_data_to_csv(data,symbol,timeframe):
    data.to_csv("../data/{}-{}.csv".format(symbol,timeframe))

In [3]:
data_btc = import_data_from_multiple_csv(data_path,"BTCUSDT","4h")

In [4]:
data_btc

,Open,High,Low,Close,Volumn,Close Time,Quote Asset Volumn,Number of Trades,Taker Buy Base Asset Volumn,Taker Buy Quote Asset Volumn,Ignore,Date Time
Open Time,,,,,,,,,,,,
1502942400000,4261.48,4349.99,4261.32,4349.99,82.088865,1502956799999,3.531943e+05,334,64.013727,2.756474e+05,8048.127886,2017-08-17 04:00:00+00:00
1502956800000,4333.32,4485.39,4333.32,4427.30,63.619882,1502971199999,2.825012e+05,248,58.787633,2.610541e+05,8020.698096,2017-08-17 08:00:00+00:00
1502971200000,4436.06,4485.39,4333.42,4352.34,174.562001,1502985599999,7.742388e+05,858,125.184133,5.554198e+05,8133.190658,2017-08-17 12:00:00+00:00
1502985600000,4352.33,4354.84,4200.74,4325.23,225.109716,1502999999999,9.652911e+05,986,165.036363,7.078082e+05,8425.112852,2017-08-17 16:00:00+00:00
1503000000000,4307.56,4369.69,4258.56,4285.08,249.769913,1503014399999,1.079545e+06,1001,203.226685,8.782870e+05,8733.911395,2017-08-17 20:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1672459200000,16552.46,16568.12,16531.00,16565.09,15808.949580,1672473599999,2.616413e+08,481363,7954.873740,1.316568e+08,0.000000,2022-12-31 04:00:00+00:00
1672473600000,16564.81,16583.90,16540.01,16567.15,20777.759880,1672487999999,3.440891e+08,613305,10272.892290,1.701237e+08,0.000000,2022-12-31 08:00:00+00:00
1672488000000,16567.52,16644.09,16547.12,16590.10,27839.309640,1672502399999,4.619598e+08,714377,14182.449630,2.353403e+08,0.000000,2022-12-31 12:00:00+00:00
1672502400000,16590.10,16613.30,16565.10,16570.14,16498.875100,1672516799999,2.736427e+08,509335,8241.342750,1.366889e+08,0.000000,2022-12-31 16:00:00+00:00
1672516800000,16570.14,16574.97,16470.00,16542.40,17909.486760,1672531199999,2.962153e+08,502335,8628.775970,1.427193e+08,0.000000,2022-12-31 20:00:00+00:00

In [ ]:
data_btc

In [5]:
write_data_to_csv(data_btc,symbol="BTCUSDT",timeframe="4h")

In [8]:
data_btc["Swing"]=(data_btc["High"]-data_btc["Low"])/data_btc["Close"]

In [9]:
data_btc["Swing"].describe()

count    11760.000000
mean         0.023548
std          0.020626
min          0.001220
25%          0.011302
50%          0.017906
75%          0.028839
max          0.343748
Name: Swing, dtype: float64