In [9]:
import pandas as pd
import numpy as np
import glob

In [10]:
data_path = "/home/andy/CryptoTradingPlatform/Historical"

def import_data_from_multiple_csv(path,symbol,interval):
   
    col_names = ["Open","High","Low","Close","Volumn","Close Time", "Quote Asset Volumn", "Number of Trades", "Taker Buy Base Asset Volumn", "Taker Buy Quote Asset Volumn", "Ignore" ]
    filenames = glob.glob("{}/{}/{}/*.csv".format(path,interval,symbol))
    dfs = []

    for filename in filenames:
        dfs.append(pd.read_csv(filename, names = col_names))

    data = pd.concat(dfs)
    data.index.name = "Date"

    data = data.sort_index(ascending=True)

    data["Date Time"] = pd.to_datetime(data.index,unit="ms",utc=True)

    data.index.name = "Open Time"

    return data

def write_data_to_csv(data,symbol,timeframe):
    data.to_csv("../data/{}-{}.csv".format(symbol,timeframe))

In [12]:
data_btc = import_data_from_multiple_csv(data_path,"BTCUSDT","1m")

In [7]:
data_btc

,Open,High,Low,Close,Volumn,Close Time,Quote Asset Volumn,Number of Trades,Taker Buy Base Asset Volumn,Taker Buy Quote Asset Volumn,Ignore,Date Time
Open Time,,,,,,,,,,,,
1502942400000,4261.48,4261.48,4261.48,4261.48,1.775183,1502942459999,7.564907e+03,3,0.075183,320.390851,7960.540180,2017-08-17 04:00:00+00:00
1502942460000,4261.48,4261.48,4261.48,4261.48,0.000000,1502942519999,0.000000e+00,0,0.000000,0.000000,7960.452630,2017-08-17 04:01:00+00:00
1502942520000,4280.56,4280.56,4280.56,4280.56,0.261074,1502942579999,1.117543e+03,2,0.261074,1117.542921,7960.375295,2017-08-17 04:02:00+00:00
1502942580000,4261.48,4261.48,4261.48,4261.48,0.012008,1502942639999,5.117185e+01,3,0.012008,51.171852,7960.375295,2017-08-17 04:03:00+00:00
1502942640000,4261.48,4261.48,4261.48,4261.48,0.140796,1502942699999,5.999993e+02,1,0.140796,599.999338,7960.375295,2017-08-17 04:04:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...
1672530900000,16540.42,16540.92,16537.71,16539.28,36.236830,1672530959999,5.993276e+05,1551,16.202690,267981.327058,0.000000,2022-12-31 23:55:00+00:00
1672530960000,16538.65,16540.53,16538.38,16540.52,38.588400,1672531019999,6.382267e+05,1536,16.977850,280806.359416,0.000000,2022-12-31 23:56:00+00:00
1672531020000,16540.52,16540.79,16535.05,16537.78,53.359780,1672531079999,8.824495e+05,2088,19.408100,320963.893237,0.000000,2022-12-31 23:57:00+00:00
1672531080000,16537.78,16538.81,16536.42,16536.42,28.882390,1672531139999,4.776434e+05,1267,11.657510,192790.564888,0.000000,2022-12-31 23:58:00+00:00
1672531140000,16536.81,16544.47,16536.23,16542.40,69.999440,1672531199999,1.157778e+06,2536,41.588510,687869.501228,0.000000,2022-12-31 23:59:00+00:00

In [ ]:
data_btc

In [13]:
write_data_to_csv(data_btc,symbol="BTCUSDT",timeframe="1m")

In [ ]:
data_eth = import_data_from_multiple_csv(data_path,"ETHUSDT","1d")

In [ ]:
data_eth

In [ ]:
write_data_to_csv(data_btc,symbol="ETHUSDT",timeframe="1d")

In [ ]:
inner = pd.concat([data_btc,data_eth],axis=1,join="inner")

In [ ]:
inner